version: '3.5'
networks:
  IMNetwork:
    name: IMNetwork
    driver: bridge
services:
  imredis:
    image: "redis:latest"
    container_name: imredis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "6379:6379"
    networks:
      - IMNetwork
  immongo:
    image: "mongo:latest"
    container_name: immongo
    ports: 
      - "27017:27017"
    networks:
      - IMNetwork
  imapi:
    image: lpovalle/api_instrumentos_musicales:prueba4
    container_name: imapi
    ports:
      - "3000:3000"
    depends_on:
      - imredis
      - immongo
    networks:
      - IMNetwork  
  crud:
    image: lpovalle/crud:prueba1
    container_name: crud
    ports: 
      - "8000:4200"
    networks:
      - IMNetwork
